### ISSUE TITLE
virtualenv.py fails

### ISSUE THREAD

**Issue by pzhine** [Strider-CD/strider-python#7]
When I run a test, I get this result during the `environment` phase.

```python
# Config merged from strider.json
$ virtualenv.py /strider/builds/.venv python 135ms
Please use the *system* python to run this script
Traceback (most recent call last):
  File "/usr/lib/node_modules/strider/node_modules/strider-python/thirdparty/virtualenv.py", line 2471, in <module>
    main()
  File "/usr/lib/node_modules/strider/node_modules/strider-python/thirdparty/virtualenv.py", line 942, in main
    never_download=options.never_download)
  File "/usr/lib/node_modules/strider/node_modules/strider-python/thirdparty/virtualenv.py", line 1043, in create_environment
    site_packages=site_packages, clear=clear))
  File "/strider/builds/.venv/lib/python2.7/posixpath.py", line 343, in abspath
    if not isabs(path):
  File "/strider/builds/.venv/lib/python2.7/posixpath.py", line 53, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by knownasilya** [comment]
Closing since this seems like a python issue. If otherwise, please reopen or comment.
